### PR TITLE
Conda package

### PR DESCRIPTION
**Pull request by sdebionne**
This is tentative to build a conda package for `asynch`.

### CODE REVIEW

**Comment by sdebionne** [comment]
@fquintero82 Diner is served (the recipe works).

**Comment by fquintero82** [comment]
Sam , you can't imagine how we really appreciate this. Really.
I am gonna start playing with it now!

**Comment by sdebionne** [comment]
@fquintero82 Did you manage to build the package?

**Comment by sdebionne** [comment]
Read this before using your package on the HPC infra:

https://conda-forge.org/docs/user/tipsandtricks.html#using-external-message-passing-interface-mpi-libraries

**Comment by fquintero82** [comment]
@sdebionne Sam, i tried to install the package in a new environment (b2) and got this error. any idea?
btw, sorry about daft punk ...

(base) $ conda env update -n b2 --file meta.yaml

 ERROR REPORT 

    Traceback (most recent call last):
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call_                                                                                                                     _
        return func(*args, **kwargs)
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/conda_env/cli/main_update.py", line 67, in                                                                                                                      execute
        spec = install_specs.detect(name=name, filename=expand(args.file),
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/conda_env/specs/__init__.py", line 43, in d                                                                                                                     etect
        if spec.can_handle():
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/conda_env/specs/yaml_file.py", line 18, in                                                                                                                      can_handle
        self._environment = env.from_file(self.filename)
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/conda_env/env.py", line 160, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/conda_env/env.py", line 141, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/conda/common/serialize.py", line 67, in yam                                                                                                                     l_safe_load
        return yaml.safe_load(string, version="1.2")
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/ruamel_yaml/main.py", line 980, in safe_loa                                                                                                                     d
        return load(stream, SafeLoader, version)
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/ruamel_yaml/constructor.py", line 109, in g                                                                                                                     et_single_data
        node = self.composer.get_single_node()
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/ruamel_yaml/composer.py", line 73, in get_s                                                                                                                     ingle_node
        self.parser.get_event()
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/ruamel_yaml/parser.py", line 163, in get_ev                                                                                                                     ent
        self.current_event = self.state()
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/ruamel_yaml/parser.py", line 177, in parse_                                                                                                                     stream_start
        token.move_comment(self.scanner.peek_token())
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/ruamel_yaml/scanner.py", line 182, in peek_                                                                                                                     token
        self.fetch_more_tokens()
      File "/home/fquinteroduque/anaconda3/lib/python3.8/site-packages/ruamel_yaml/scanner.py", line 317, in fetch                                                                                                                     _more_tokens
        raise ScannerError(
    ruamel_yaml.scanner.ScannerError: while scanning for the next token
    found character '%' that cannot start any token
      in "<unicode string>", line 2, column 2:
        {% if GIT_DESCRIBE_TAG is defined %}
         ^ (line: 2)

`$ /home/fquinteroduque/anaconda3/bin/conda-env update -n b2 --file meta.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/fquinteroduque/anaconda3/bin/conda
             CONDA_PREFIX=/home/fquinteroduque/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/fquinteroduque/anaconda3/bin/python
               CONDA_ROOT=/home/fquinteroduque/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                     PATH=/home/fquinteroduque/anaconda3/bin:/home/fquinteroduque/anaconda3/bin:
                          /home/fquinteroduque/anaconda3/condabin:/usr/lib64/qt-3.3/bin:/usr/loc
                          al/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/fquinterodu
                          que/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/fquinteroduque/anaconda3
            shell level : 1
       user config file : /home/fquinteroduque/.condarc
 populated config files :
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.12=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/fquinteroduque/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/fquinteroduque/anaconda3/pkgs
                          /home/fquinteroduque/.conda/pkgs
       envs directories : /home/fquinteroduque/anaconda3/envs
                          /home/fquinteroduque/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/2.6.32-754.25.1.el6.centos.plus.x86_64 c                                                                                                                     entos/6.10 glibc/2.12
                UID:GID : 505:505
             netrc file : None
           offline mode : False

**Comment by sdebionne** [comment]
@fquintero82 This is not how it works. You need to build the package with the recipe first:

1. Install conda-build if not installed yet
2. Build the package
3. Install the package from the "local" channel in the ifcfq env
4. Eventually upload the package to anaconda to a newly created IFC channel

```
$ conda install conda-build -n base
$ conda build <async folder>/conda -c conda-forge
$ conda install async -c local -c conda-forge -n ifcfq
```

**Comment by fquintero82** [comment]
@sdebionne  It's alive !

Sam, it works! This is very cool.
The issue i was trying to solve (incompatibility with the hdf version of the system) is still causing problems. But that aside, thank you very much for sharing this recipe with us.

$ conda activate ifcfq
$ ~/anaconda3/envs/ifcfq/bin/asynch clearcreek.gbl
Beginning initialization...
*****************************
Reading global file...
Loading network...
Partitioning network...
Loading parameters...
Reading dam and reservoir data...
Setting up numerical error data...
Initializing model...
Loading initial conditions...
Loading forcings...
Loading output data information...
Finalizing network...
Calculating initial step sizes...

Model type is 254.
Process 0 (1 total) is good to go with 6359 links.
Finished initialization. Total time for initialization: 1.047664


Computing solution at each link...
************************************
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
**Headers are 1.8.5, library is 1.10.6**

**Comment by sdebionne** [comment]
When using Conda you should not modify `LD_LIBRARY_PATH` and I suspect that the activates scripts on the HPC cluster do that. Or is it on your local machine?

Could you run:
```
ldd ~/anaconda3/envs/ifcfq/bin/asynch
```
to check where hdf5 comes from. It should be from `~/anaconda3/envs/ifcfq/lib` but apparently the system one is before in the path.

**Pull request merged**
